name: linux-tests
on:
  push:
    branches: [ stable, WIP ]
  pull_request:
    branches: [ stable, WIP ]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Executable
      working-directory: scr
      run: |
        chmod +x build-linux.sh
        ./build-linux.sh
    - name: Archive Executable
      uses: actions/upload-artifact@v4
      with:
        name: py-shield-linux
        path: scr/py-shield
  
  linux-obfuscation:
    needs: linux-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download Executable
      uses: actions/download-artifact@v4
      with:
        name: py-shield-linux
        path: "examples"
    - name: Preparation For Tests
      working-directory: examples
      run: |
        chmod +x py-shield
        mv py-shield multifile/
        rm -rf multifile/obfuscated
    - name: Obfuscation
      working-directory: examples/multifile
      run: |
        ./py-shield obfuscate --aes --hashdata --fernet --chacha --salsa --base64 --recursive 4 --no-input --files lib.py main.py
    - name: Testing
      working-directory: examples/multifile/obfuscated
      run: |
        OUTPUT=$(python main.py)
        echo "Output: $OUTPUT"
        echo "Result: "
        if [ "$OUTPUT" = "hello world" ]; then
          echo "Success: main.py output contains 'hello world'"
        else
          echo "Failure: main.py output does not contain 'hello world'"
          exit 1
        fi
  
  linux-obfuscation-legacy:
    needs: linux-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download Executable
      uses: actions/download-artifact@v4
      with:
        name: py-shield-linux
        path: "examples"
    - name: Preparation For Tests
      working-directory: examples
      run: |
        chmod +x py-shield
        mv py-shield onefile/
        rm -rf onefile/obfuscated
    - name: Obfuscation
      working-directory: examples/onefile
      run: |
        ./py-shield obfuscatelegacy --no-input --mode 3 --loops 6 --files main.py
    - name: Testing
      working-directory: examples/onefile/obfuscated
      run: |
        OUTPUT=$(python main.py)
        echo "Output: $OUTPUT"
        echo "Result: "
        if [ "$OUTPUT" = "hello world" ]; then
          echo "Success: main.py output contains 'hello world'"
        else
          echo "Failure: main.py output does not contain 'hello world'"
          exit 1
        fi
