name: MacOS tests

on:
  push:
    branches: [ stable, WIP ]
  pull_request:
    branches: [ stable, WIP ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Executable
      working-directory: scr
      run: |
        chmod +x build-mac.sh
        ./build-mac.sh
    - name: Archive Executable
      uses: actions/upload-artifact@v4
      with:
        name: py-shield-mac
        path: scr/py-shield